before:
  hooks:
    - go mod download
signs:
  - artifacts: checksum
builds:
  - binary: miniflux_bot
    id: linux_x86
    env:
      - CGO_ENABLED=1
      - CC=/usr/local/opt/musl-cross/bin/x86_64-linux-musl-gcc
      - CXX=/usr/local/opt/musl-cross/bin/x86_64-linux-musl-g++
    ldflags:
      - "-linkmode external -extldflags -static"
      - "-X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    goos:
      - linux
    goarch:
      - amd64
  - binary: miniflux_bot
    id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
